### PR TITLE
Fix for responsive image

### PR DESCRIPTION
**Pull request by ghost**
Fix for responsive image

Also here https://github.com/PrestaShop/PrestaShop/pull/14323

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PrestaShark,

What is the exact issue with this module?
**Without PR:**
image

**With PR:**
image
image

Thanks!

**Comment by ghost** [comment]
@khouloudbelguith  Uploaded image was not responsive in front office ;)

**Comment by khouloudbelguith** [comment]
@PrestaShark, can you please provide us a screenshot about your issue.

Thanks!

**Comment by ghost** [comment]
Take a look here https://raw.githubusercontent.com/PrestaShop/ps_advertising/master/ps_advertising.tpl image dont have responsive class. So if You upload any image it will break responsiveness of front office

**Comment by khouloudbelguith** [comment]
@PrestaShark, I tried with PS1.7.6.5 and  ps_advertising module v1.0.2 => it is OK
image

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith QA :heavy_check_mark:  ?

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have no issue without this PR.
The picture is well displayed in the FO when using a phone.
What do you think?

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith I have misread your comment. Sorry :yum:

**Comment by sarahdib** [comment]
@PrestaShark could you provide us a scenario in order to test your pull request ?

**Comment by sarahdib** [comment]
@PrestaShark since we cant reproduce the issue we can't validate the pull request.

If you reproduce the problem and provide us more detail you can reopen this pull request.

Have a nice day

**Pull request closed without merging**
